# Generated by Django 4.2.4 on 2023-08-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('wid', models.IntegerField(primary_key=True, serialize=False)),
                ('workerName', models.CharField(max_length=50)),
            ],
        ),
    ]
