# Generated by Django 3.0.8 on 2023-08-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worker',
            table='Worker',
        ),
    ]
